### ISSUE TITLE
ItemsPage does not show when a list is selected immediately after startup

### ISSUE THREAD

**Issue by kugiigi** [kugiigi/talaan-app#6]
## Steps to reproduce
1. Open the app.
2, Immediately after opening, select a list

## Expected Result
The items page should be displayed with the data of the selected list

## Actual Result
The selected list is highlighted but the items page does not show.

**Comment by Danfro** [comment]
For the timeperiod where this behaviour occurs you can multiselect several lists. And in the top right of the item you do get symbols to save, delete, ... the item.
 Maybe this gives you a hint where to look at? I do not understand enough of your code.

**Comment by kugiigi** [comment]
For now, the solution would be to display activity indicator until the itemspage is fully loaded.
